SUDOKU_SIZE = 9
CELL_SIZE = SUDOKU_SIZE**(1/2)
TOTAL_GRIDS = SUDOKU_SIZE * SUDOKU_SIZE
TOTAL_ACTIONS = TOTAL_GRIDS * SUDOKU_SIZE

WIN_HEIGHT = 600
WIN_WIDTH = 600
MARGIN = 30

TRAIN_PATH = './data/sudoku.csv'
MODEL_PATH = "./models/current_policy.model"